volumes:
    tshock-data:
    worlds-data:
    plugins-data:

services:
    terraria:
        image: barbarbar338/tshock:buildx-latest
        container_name: terraria
        restart: unless-stopped
        ports:
            - 7777:7777 # Terraria port
            - 7878:7878 # TShock REST API port
        volumes:
            - tshock-data:/tshock
            - worlds-data:/worlds
            - plugins-data:/plugins
        environment:
            WORLDNAME: myworld
            MOTD: TShock on Docker!
            DIFFICULTY: 0
            AUTOCREATE: 1