#https://stackoverflow.com/a/68407424

name: Build Image

on:
    workflow_run:
        workflows: ["check"]
        types: [completed]

jobs:
    check:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - run: git submodule update --init --recursive
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3
        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64,linux/arm64,linux/arm/v7,windows/amd64
            push: true
            tags: barbarbar338/tshock:buildx-latest
