# https://stackoverflow.com/a/68407424

name: check

on:
    schedule:
        - cron:  "30 5 * * *"

    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - run: exit $(curl -s https://api.github.com/repos/Pryaxis/Tshock/commits/heads/general-devel | jq -r "((now - (.commit.author.date | fromdateiso8601) )  / (60*60*24)  | trunc)")
