# https://stackoverflow.com/a/68407424

name: check

on:
    schedule:
        - cron:  "30 5 * * *"
    push:
        branches: [main]

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - run: ./checkCommit.sh
