name: Check Last Commit & Build

on:
    schedule:
        - cron:  "30 5 * * *"
    push:
        branches: [main]

jobs:
    check-commit-date:
        name: Check Last Commit Date
        runs-on: ubuntu-latest

        steps:
            - name: Get Latest Commit Date
              id: commit-date
              run: |
                repoURL="https://api.github.com/repos/Pryaxis/Tshock/commits/heads/general-devel"
                commitDate=$(curl -s $repoURL | jq -r ".commit.author.date" | xargs -I{} date -d {} +%s)
                echo "::set-output name=date::$commitDate"

    cancel-process:
        name: Cancel Build Process
        needs: check-commit-date
        runs-on: ubuntu-latest
        if: steps.commit-date.outputs.date < (formatDate(now(), 'yyyy-MM-ddTHH:mm:ssZZ'))

        steps:
            - name: Cancel Workflow
              run: echo "Process cancelled because there is no new commit."

    build:
        name: Build & Push Image
        needs: check-commit-date
        runs-on: ubuntu-latest
        if: steps.commit-date.outputs.date >= (formatDate(now(), 'yyyy-MM-ddTHH:mm:ssZZ'))

        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                context: .
                platforms: linux/amd64,linux/arm64,linux/arm/v7,windows/amd64
                push: true
                tags: barbarbar338/tshock:buildx-latest

