name: Manual Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build & Push Image
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Login to GitHub Container Registry (GHCR)
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Build and push
          uses: docker/build-push-action@v5
          with:
            context: .
            platforms: linux/amd64,linux/arm64,linux/arm/v7
            push: true
            tags: |
              barbarbar338/tshock:buildx-latest
              ghcr.io/${{ github.repository_owner }}/tshock:buildx-latest
            cache-from: type=gha
            cache-to: type=gha,mode=max
